# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 20
#
#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Professor"  # Title of the link.
#  url = "authors/admin/"  # Widget Page folder name.
#  weight = 2  # Position of the link in the navigation bar.

[[main]]
  name = "Members"  # Title of the link.
  url = "people/"  # Widget Page folder name.
  weight = 3  # Position of the link in the navigation bar.
  identifier = "people"

[[main]]
  name = "Current members"  # Title of the link.
  url = "people/"  # Widget Page folder name.
  weight = 1  # Position of the link in the navigation bar.
  parent = "people"

  [[main]]
  name = "Alumni"  # Title of the link.
  url = "alumni/"  # Widget Page folder name.
  weight = 2  # Position of the link in the navigation bar.
  parent = "people"

[[main]]
  name = "Research"  # Title of the link.
  url = "project/"  # Widget Page folder name.
  weight = 4  # Position of the link in the navigation bar.
  hasChildren = true
  identifier = "researchitems"

  [[main]]
  name = "Research Overview"
  url = "research/"
  weight = 1
  parent = "researchitems"

  [[main]]
  name = "Solvation and Electrified Interfaces"
  url = "project/solvationandelectrifiedinterfaces/"
  weight = 2
  parent = "researchitems"

  [[main]]
  name = "Materials Screening"
  url = "project/materialscreening/"
  weight = 3
  parent = "researchitems"

  [[main]]
  name = "Multiscale modeling"
  url = "project/multiscalemodeling/"
  weight = 4
  parent = "researchitems"

#[[main]]
#  name = "Research"  # Title of the link.
#  url = "research/"  # Widget Page folder name.
#  weight = 4  # Position of the link in the navigation bar.
#  hasChildren = true
#  identifier = "researchitems"
#
#[[main]]
#  name = "Overview"
#  url = "research/"
#  weight = 1
#  parent = "researchitems"
#
#[[main]]
#  name = "General interest"
#  url = "project_general/generalresearchgoals/"
#  weight = 2
#  parent = "researchitems"
#
#[[main]]
#  name = "Electrochemistry at interfaces"
#  url = "project/electrochemistrycomplexelectrifiedinterfaces/"
#  weight = 3
#  parent = "researchitems"
#
#[[main]]
#  name = "Multi-scale design"
#  url = "project/multiscaledesign/"
#  weight = 4
#  parent = "researchitems"

[[main]]
  name = "Software"  # Title of the link.
  url = "development/"  # Widget Page folder name.
  weight = 5  # Position of the link in the navigation bar.
  hasChildren = true
  identifier = "softwareitems"

[[main]]
  name = "MPBE/FHI-aims"
  url = "software/mpbe/"
  weight = 1
  parent = "softwareitems"

[[main]]
  name = "CatINT/COMSOL"
  url = "software/catint/"
  weight = 2
  parent = "softwareitems"

[[main]]
  name = "Publications"  # Title of the link.
  url = "my-publications/"  # Widget Page folder name.
  weight = 6  # Position of the link in the navigation bar.

[[main]]
  name = "Gallery"  # Title of the link.
  url = "gallery/"  # Widget Page folder name.
  weight = 6  # Position of the link in the navigation bar.

[[main]]
  name = "Contact"  # Title of the link.
  url = "contact/"  # Widget Page folder name.
  weight = 7  # Position of the link in the navigation bar.

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
